=== HBDSolutions/highstreetgym/public/xml/dtd/scheduleAdd.dtd
<!ELEMENT schedules (schedule+)>
<!ELEMENT schedule (trainer_id, class_id, day_of_week, start_time, end_time, max_capacity?)>
<!ELEMENT trainer_id (#PCDATA)>
<!ELEMENT class_id (#PCDATA)>
<!ELEMENT day_of_week (#PCDATA)>
<!ATTLIST day_of_week day CDATA #IMPLIED>
<!ELEMENT start_time (#PCDATA)>
<!ELEMENT end_time (#PCDATA)>
<!ELEMENT max_capacity (#PCDATA)>

=== HBDSolutions/highstreetgym/.history/XMLDocuments/scheduleAdd_20251114151700.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="timetable.xsl"?>
<!DOCTYPE schedules SYSTEM "../public/xml/dtd/scheduleAdd.dtd">
<schedules>
  <schedule>
    <trainer_id>1</trainer_id>
    <class_id>3</class_id>
    <day_of_week day="Mon">Mon</day_of_week>
    <start_time>10:00</start_time>
    <end_time>10:45</end_time>
    <max_capacity>5</max_capacity>
  </schedule>
  <schedule>
    <trainer_id>1</trainer_id>
    <class_id>3</class_id>
    <day_of_week day="Wed">Wed</day_of_week>
    <start_time>10:00</start_time>
    <end_time>10:45</end_time>
    <max_capacity>5</max_capacity>
  </schedule>
</schedules>
